import type { Application, User, Note, ApplicationStatus } from "./types"

export const sampleUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    role: "management",
    avatar: "/professional-woman-diverse.png",
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike.chen@company.com",
    role: "associate",
    avatar: "/professional-man.png",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@company.com",
    role: "associate",
    avatar: "/professional-woman-diverse.png",
  },
  {
    id: "4",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "management",
    avatar: "/professional-man.png",
  },
]

export const sampleNotes: Note[] = [
  {
    id: "1",
    applicationId: "1",
    authorId: "2",
    authorName: "Mike Chen",
    content: "Strong technical background, excellent portfolio. Recommended for technical interview.",
    createdAt: "2024-01-15T10:30:00Z",
    isInternal: true,
  },
  {
    id: "2",
    applicationId: "1",
    authorId: "1",
    authorName: "Sarah Johnson",
    content: "Approved for next round. Schedule interview with engineering team.",
    createdAt: "2024-01-15T14:45:00Z",
    isInternal: true,
  },
  {
    id: "3",
    applicationId: "3",
    authorId: "3",
    authorName: "Emily Rodriguez",
    content: "Missing portfolio link. Requested additional information from candidate.",
    createdAt: "2024-01-14T09:15:00Z",
    isInternal: true,
  },
]

export const sampleApplications: Application[] = [
  {
    id: "1",
    firstName: "Alex",
    lastName: "Thompson",
    email: "alex.thompson@email.com",
    position: "Frontend Engineer",
    majorAndGraduation: "Computer Science, 2019",
    growthMetrics: "Increased user engagement by 45% through React optimization",
    previousRole: "Senior Frontend Developer at TechCorp",
    resumeUrl: "https://example.com/resume-alex.pdf",
    applicationDate: "2024-01-15",
    status: "shortlisted",
    assignedReviewer: "Mike Chen",
    notes: sampleNotes.filter((note) => note.applicationId === "1"),
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T14:45:00Z",
  },
  {
    id: "2",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria.garcia@email.com",
    position: "Frontend Engineer",
    majorAndGraduation: "Computer Science, 2022",
    growthMetrics: "Improved website load times by 30% using modern CSS techniques",
    previousRole: "Frontend Developer at StartupABC",
    resumeUrl: "https://example.com/resume-maria.pdf",
    applicationDate: "2024-01-14",
    status: "interview",
    assignedReviewer: "Emily Rodriguez",
    notes: [],
    createdAt: "2024-01-14T10:30:00Z",
    updatedAt: "2024-01-14T10:30:00Z",
  },
  {
    id: "3",
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@email.com",
    position: "Backend Engineer",
    majorAndGraduation: "Computer Science, 2018",
    growthMetrics: "Reduced API response times by 60% through database optimization",
    previousRole: "Backend Engineer at CloudTech",
    resumeUrl: "https://example.com/resume-james.pdf",
    applicationDate: "2024-01-14",
    status: "submitted",
    assignedReviewer: "Emily Rodriguez",
    notes: sampleNotes.filter((note) => note.applicationId === "3"),
    createdAt: "2024-01-14T09:00:00Z",
    updatedAt: "2024-01-14T09:15:00Z",
  },
  {
    id: "4",
    firstName: "Lisa",
    lastName: "Chen",
    email: "lisa.chen@email.com",
    position: "Backend Engineer",
    majorAndGraduation: "Computer Science, 2023",
    growthMetrics: "Built REST API serving 10k+ daily requests with 99.9% uptime",
    previousRole: "Backend Developer Intern at DataFlow",
    resumeUrl: "https://example.com/resume-lisa.pdf",
    applicationDate: "2024-01-13",
    status: "submitted",
    assignedReviewer: "Mike Chen",
    notes: [],
    createdAt: "2024-01-13T16:20:00Z",
    updatedAt: "2024-01-13T16:20:00Z",
  },
  {
    id: "5",
    firstName: "Robert",
    lastName: "Martinez",
    email: "robert.martinez@email.com",
    position: "Frontend Engineer",
    majorAndGraduation: "Web Development Bootcamp, 2023",
    growthMetrics: "Increased mobile conversion rates by 25% through responsive design",
    previousRole: "Junior Developer at WebStudio",
    resumeUrl: "https://example.com/resume-robert.pdf",
    applicationDate: "2024-01-12",
    status: "submitted",
    assignedReviewer: "Mike Chen",
    notes: [],
    createdAt: "2024-01-12T11:45:00Z",
    updatedAt: "2024-01-12T15:30:00Z",
  },
  {
    id: "6",
    firstName: "Jennifer",
    lastName: "Lee",
    email: "jennifer.lee@email.com",
    position: "Frontend Engineer",
    majorAndGraduation: "Software Engineering, 2017",
    growthMetrics: "Led team that delivered 40% faster page loads across all products",
    previousRole: "Frontend Engineer at InnovateTech",
    resumeUrl: "https://example.com/resume-jennifer.pdf",
    applicationDate: "2024-01-11",
    status: "interview",
    assignedReviewer: "Sarah Johnson",
    notes: [],
    createdAt: "2024-01-11T13:15:00Z",
    updatedAt: "2024-01-11T13:15:00Z",
  },
  {
    id: "7",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@email.com",
    position: "Backend Engineer",
    majorAndGraduation: "Software Engineering, 2016",
    growthMetrics: "Scaled microservices to handle 500% traffic increase with zero downtime",
    previousRole: "Backend Engineer at ScaleTech",
    resumeUrl: "https://example.com/resume-michael.pdf",
    applicationDate: "2024-01-10",
    status: "shortlisted",
    assignedReviewer: "David Kim",
    notes: [],
    createdAt: "2024-01-10T14:20:00Z",
    updatedAt: "2024-01-10T16:30:00Z",
  },
  {
    id: "8",
    firstName: "Amanda",
    lastName: "Davis",
    email: "amanda.davis@email.com",
    position: "Backend Engineer",
    majorAndGraduation: "Computer Science, 2023",
    growthMetrics: "Optimized database queries resulting in 35% faster data retrieval",
    previousRole: "Backend Developer at StartupFlow",
    resumeUrl: "https://example.com/resume-amanda.pdf",
    applicationDate: "2024-01-09",
    status: "submitted",
    assignedReviewer: "Emily Rodriguez",
    notes: [],
    createdAt: "2024-01-09T11:10:00Z",
    updatedAt: "2024-01-09T15:45:00Z",
  },
]

export const positions = [
  "Frontend Engineer",
  "Backend Engineer",
]

export const statusColors: Record<ApplicationStatus, string> = {
  submitted: "bg-blue-50 text-blue-700 border-blue-200",
  interview: "bg-orange-50 text-orange-700 border-orange-200",
  shortlisted: "bg-green-50 text-green-700 border-green-200",
}

export const statusLabels: Record<ApplicationStatus, string> = {
  submitted: "3) Submitted Application",
  interview: "2) Invited to Interview",
  shortlisted: "1) Shortlisted",
}
